ARTIST_CATEGORIES = {
	"Hip Hop": [
		"$uicideBoy$",
		"100s",
		"2 Chainz",
		"21 Savage",
		"2Pac",
		"3rd Bass",
		"50 Cent",
		"6LACK",
		"6ix9ine",
		"A$AP Ferg",
		"A$AP Mob",
		"A$AP Rocky",
		"ASM",
		"Ab-Soul",
		"Aesop Rock",
		"Akua Naru",
		"Aloe Blacc",
		"Andre Nickatina",
		"Anti-Lilly & Phoniks",
		"Apollo Brown",
		"Arrested Development",
		"BJ The Chicago Kid",
		"Babu",
		"Bass Santana",
		"Beastie Boys",
		"Big Baby Scumbag",
		"Big Boi",
		"Big K.R.I.T.",
		"Big L",
		"Big Nick",
		"Big Pun",
		"Big Sean",
		"Big Shaq",
		"Big Tuck",
		"Bishop Nehru",
		"Black Sheep",
		"Black Star",
		"Blood Orange",
		"Blueface",
		"Bobby Shmurda",
		"Boogie",
		"Brick Wolfpack",
		"Bryson Tiller",
		"Busta Rhymes",
		"CL",
		"Cardi B",
		"Chaz",
		"Chester Watson",
		"Childish Gambino",
		"Chophouze",
		"Chuggo",
		"Chuuwee",
		"City Morgue",
		"Comethazine",
		"Count Bass D",
		"Curren$y",
		"DJ ESCO",
		"DJ Esco",
		"DJ Snake",
		"DMX",
		"DaBaby",
		"Danger Doom",
		"Danny Brown",
		"Dave",
		"Dead Prez",
		"Death Grips",
		"Declaime",
		"Del The Funky Homosapien",
		"Deltron 3030",
		"Denzel Curry",
		"Denzil Porter",
		"Devin The Dude",
		"Die Antwoord",
		"Digable Planets",
		"Dom Kennedy",
		"Doobmin",
		"Doom",
		"Doron Lev",
		"Dorrough Music",
		"Dr. Dre",
		"Drake",
		"Dreezy",
		"Dusty Ohms",
		"EARTHGANG",
		"EPMD",
		"Ed Scissor",
		"Eighth Wonder",
		"Eminem",
		"Eric B. & Rakim",
		"Evil Nine / Aesop Rock",
		"Fetty Wap",
		"Flatbush Zombies",
		"Flying Lotus",
		"Footsie",
		"Foreign Beggars",
		"Frayser Boy",
		"Freddie Gibbs",
		"Fredro Starr",
		"Freshie",
		"Future",
		"G Perico",
		"GZA",
		"Gang Starr",
		"Gangrene",
		"Gangsta Blac",
		"Gawd Status",
		"Geto Boys",
		"Ghostface Killah",
		"Gmcfosho",
		"Gnarls Barkley",
		"Guru",
		"Hail Mary Mallon",
		"Handsome Boy Modeling School",
		"Hell Razah",
		"IDK",
		"ILL Bill",
		"Ice Cube",
		"Indo G",
		"Innanet James",
		"Isaiah Rashad",
		"Ivan Ave",
		"J Capri",
		"J Dilla",
		"J Hus",
		"J.R. Donato",
		"J:Kenzo",
		"JACKBOYS",
		"JAY-Z",
		"JID",
		"Ja Rule",
		"Jay Rock",
		"Jaykae",
		"Jazz Spastiks",
		"Jeru The Damaja",
		"Jidenna",
		"Jody HiGHROLLER",
		"Joey Bada$$",
		"John Robinson",
		"Joji",
		"Josef Leimberg",
		"Juice WRLD",
		"K.M.D.",
		"KINGDEM",
		"Kanye West",
		"Kendrick Lamar",
		"Kev Brown",
		"Kholebeatz",
		"King Geedorah",
		"King Tee",
		"Knowmadic",
		"Kodak Black",
		"Krush",
		"L-Boy",
		"LL Cool J",
		"Leaders of the New School",
		"Leakaveli",
		"Lil Baby",
		"Lil Dicky",
		"Lil Skies",
		"Lil Tecca",
		"Lil Toe",
		"Lil Uzi Vert",
		"Lil Whyte",
		"Lil Windex",
		"Lil Wyte",
		"Lil Yachty",
		"Lords Of The Underground",
		"Low Profile",
		"M.O.P.",
		"MC Chris",
		"MF DOOM",
		"Mack 10",
		"MadeinTYO",
		"Mango Foo",
		"Marion Band$",
		"Masta Killa",
		"Method Man",
		"Metro Boomin",
		"Mick Jenkins",
		"Migos",
		"Mike WiLL Made-It",
		"Moneybagg Yo",
		"Montell Jordan",
		"Mos Def",
		"Nas",
		"Nebu Kiniza",
		"Nice & Smooth",
		"Nipsey Hussle",
		"O.T. Genasis",
		"OG Maco",
		"OJ Da Juiceman",
		"Odd Future",
		"Oh No",
		"Onoe Caponoe",
		"Onyx",
		"OutKast",
		"OverDoz.",
		"P-Lo",
		"Packtavists",
		"Pete Cannon",
		"Pharoahe Monch",
		"Pimp C",
		"Playboi Carti",
		"Positive K",
		"Project Pat",
		"Prophet Posse",
		"Public Enemy",
		"Quality Control",
		"Quasimoto",
		"Quin Nfn",
		"Rabbi Shlomo",
		"Rae Sremmurd",
		"Redman",
		"Rich Homie Quan",
		"Rich The Kid",
		"Riff Raff",
		"Rodney P",
		"Ronny J",
		"Salt-N-Pepa",
		"ScHoolboy Q",
		"Scarface",
		"Scienz Of Life",
		"Sheck Wes",
		"ShooterGang Kony",
		"Sir Mix-A-Lot",
		"Skee-Lo",
		"Ski Mask The Slump God",
		"Slick Rick",
		"Sly5thAve",
		"Smoke Boys",
		"Space Captain",
		"Spice 1",
		"Steve G. Lover III",
		"Sticky Fingaz",
		"Suga Free",
		"Swindle",
		"Takeoff",
		"Talib Kweli",
		"Tall Black Guy",
		"Tay-K",
		"Te'amir",
		"Tee Grizzley",
		"Terror Danjah",
		"Terror Reid",
		"Terror Squad",
		"Tha Dogg Pound",
		"The Game",
		"The Lonely Island",
		"The Notorious B.I.G.",
		"The Pharcyde",
		"The Prof",
		"The Roots",
		"The Underachievers",
		"Tommy Cash",
		"Tony J. Guy",
		"Travis Scott",
		"Tree",
		"Trent the HOOLiGAN",
		"Trick Daddy",
		"Trinidad James",
		"Trippie Redd",
		"Tunji Ige",
		"Twista",
		"Ty Talaban",
		"Tyler, The Creator",
		"UGK",
		"UnoTheActivist",
		"Vast Aire",
		"Viktor Vaughn",
		"Vince Staples",
		"WELL$",
		"Waka Flocka Flame",
		"Warren G",
		"Wax",
		"Wc And The Maad Circle",
		"Weerd Science",
		"Wildchild",
		"Wooski",
		"Wu-Tang Clan",
		"XXXTENTACION",
		"YBN Cordae",
		"YBN Nahmir",
		"Young M.A",
		"Young Thug",
		"YoungBoy Never Broke Again",
		"Zebra Katz",
		"mcashhole",
	],
	"Grime": [
		"AJ Tracey",
		"Bugzy Malone",
		"D Double E",
		"Dizzee Rascal",
		"Flowdan",
		"Jammer",
		"Jme",
		"Kano",
		"Lady Leshurr",
		"Milli Major",
		"Nadia Rose",
		"Paigey Cakey",
		"President T",
		"Pusha T",
		"Riddim Commission",
		"Skepta",
		"Stormzy",
		"Tempa T",
		"Uncle Murda",
		"Wiley",
		"Zuse",
	],
	"Electronic": [
		"Alvaro",
		"Baauer",
		"Beck",
		"Becky Hill",
		"Boys Noize",
		"Busy P",
		"Cassius",
		"Crystal Castles",
		"DJ Blyatman",
		"Daft Punk",
		"Danger",
		"Delta Heavy",
		"Destructo",
		"Digitalism",
		"Diplo",
		"Electronic",
		"Favored Nations",
		"Flight Facilities",
		"Flosstradamus",
		"Gorillaz",
		"Groove Armada",
		"HEALTH",
		"Jacuzzi",
		"KRANE",
		"LCD Soundsystem",
		"M-Beat",
		"MK",
		"MSTRKRFT",
		"Maelstrom",
		"Malaa",
		"Matoma",
		"Mercer",
		"MiM0SA",
		"Mighty Dub Katz",
		"Moby",
		"Oliver",
		"Oliver Heldens",
		"Pretty Lights",
		"Rustie",
		"Shiba San",
		"State of Mind",
		"The Chain Gang Of 1974",
		"The Hacker",
		"The Jungle Giants",
		"The Octopus Project",
		"The Prodigy",
		"Toro y Moi",
		"Valentino Khan",
		"X-Press 2",
		"Yello",
	],
	"Indie": [
		"Cake",
		"Chad VanGaalen",
		"Devendra Banhart",
		"Edie Brickell & New Bohemians",
		"José González",
		"Metronomy",
		"Modest Mouse",
		"Neon Indian",
		"Neutral Milk Hotel",
		"Peter Bjorn and John",
		"Sunset Rubdown",
		"The Burning Hell",
		"The Strokes",
		"Vampire Weekend",
		"Yeasayer",
	],
	"Computer Music": [
		"Kraftwerk",
		"Nobukazu Takemura",
		"Rei Harakami",
	],
	"DnB": [
		"Andy C",
		"Pendulum",
	],
	"Synthwave": [
		"Blank Banshee",
		"Carpenter Brut",
		"Com Truise",
		"Dan Terminus",
		"Dance With the Dead",
		"Fukkk Offf",
		"Gesaffelstein",
		"Kavinsky",
		"Kn1ght",
		"Scattle",
		"The Toxic Avenger",
		"Waveshaper",
	],
	"Rock": [
		"Art vs Science",
		"OFF!",
		"Primus",
		"Queens of the Stone Age",
		"Red Hot Chili Peppers",
		"Tenacious D",
		"The Ataris",
		"The Hives",
		"The Mars Volta",
		"The Voidz",
		"The White Stripes",
		"Wavves",
	],
	"Chiptunes": [
		"Dubmood",
		"FantomenK",
		"Fantomenk",
		"MisfitChris",
	],
	"French Electro": [
		"Breakbot",
		"Chromeo",
		"Justice",
		"Mr. Oizo",
		"Riton",
		"SebastiAn",
		"Siriusmo",
		"Sébastien Tellier",
	],
	"Synth Pop": [
		"Depeche Mode",
		"Dolby's Cube",
		"Gary Numan",
		"Kraftwerk",
		"Thomas Dolby",
	],
	"New Wave": [
		"Joy Division",
		"New Order",
		"Nite Jewel",
		"The B-52's",
	],
	"Heavy": [
		"Alexisonfire",
		"All That Remains",
		"Billx",
		"Death From Above 1979",
		"Death Grips",
		"Drive Like Jehu",
		"Gojira",
		"Lamb of God",
		"Mastodon",
		"Mindless Self Indulgence",
		"Periphery",
		"Protest The Hero",
		"The Fall of Troy",
	],
	"Jazz": [
		"Fela Kuti",
		"Ryuichi Sakamoto",
		"Takuya Kuroda",
		"The Deli",
		"Twin Danger",
		"Yazz",
		"Yusef Lateef",
	],
	"Chill": [
		"Ancient Astronauts",
		"Boards of Canada",
		"Brock Berrigan",
		"Clap! Clap!",
		"Hexsystem",
		"Jonwayne",
		"Lorn",
		"Mndsgn",
		"Nosaj Thing",
		"Sleepdealer",
		"Wun Two",
		"[bsd.u]",
	],
	"Oldies": [
		"Age of Consent",
		"Aswad",
		"Bill Withers",
		"Billy Idol",
		"Boogie Boys",
		"Boy George",
		"Bros",
		"Bruce Springsteen",
		"Bruce Willis",
		"Cameo",
		"Carmen",
		"Chaka Khan",
		"Corey Hart",
		"Curiosity Killed The Cat",
		"David Bowie",
		"Deacon Blue",
		"Deep Purple",
		"Don Henley",
		"Duran Duran",
		"Dusty Springfield",
		"Dâm-Funk",
		"Elton John",
		"Fairground Attraction",
		"Four Tops",
		"Frazier Chorus",
		"Funkadelic",
		"Gustav Holst",
		"Hue and Cry",
		"Ivana Spagna",
		"Jamiroquai",
		"Jethro Tull",
		"Jimi Hendrix",
		"Kenny Loggins",
		"Kurtis Blow",
		"Kylie Minogue",
		"Laura Branigan",
		"Level 42",
		"Los Lobos",
		"Magazine",
		"Malcolm McLaren & The Bootzilla Orchestra",
		"Marvin Gaye",
		"Melody's Echo Chamber",
		"Men Without Hats",
		"Michael Jackson",
		"New Kids On The Block",
		"Oingo Boingo",
		"Otis Redding",
		"Pet Shop Boys",
		"Pixies",
		"Prefab Sprout",
		"Queen",
		"Rick Astley",
		"Rick James",
		"Rick Springfield",
		"Roachford",
		"Sam Brown",
		"Samantha Fox",
		"Shakin' Stevens",
		"Simply Red",
		"Smokey Robinson & The Miracles",
		"Sonia",
		"Soul II Soul",
		"Sporto Kantès",
		"Stereolab",
		"Stevie Wonder",
		"Styx",
		"Supertramp",
		"T'Pau",
		"Taylor Dayne",
		"Tears For Fears",
		"Terence Trent D'Arby",
		"The Clash",
		"The Darling Buds",
		"The Doors",
		"The O'Jays",
		"The Pasadenas",
		"The Police",
		"The Primitives",
		"The Reynolds Girls",
		"The Stranglers",
		"The Supremes",
		"The Temptations",
		"Tiffany",
		"Toba",
		"Tom Waits",
		"Transvision Vamp",
		"Twin Shadow",
		"Westworld",
		"Wilson Pickett",
		"Yaz",
		"a-ha",
	],
	"Reggae": [
		"Beenie Man",
		"Buju Banton",
		"Gappy Ranks",
		"Gregory Isaacs",
		"Max Romeo",
		"Maxi Priest",
		"Red Rat",
	],
	"Prog": [
		"Emerson, Lake & Palmer",
		"Gentle Giant",
	],
	"IGNORE": [
		"10LEC6",
		"88rising",
		"Acid Washed",
		"Agoria",
		"Alan Braxe",
		"Alex Gopher",
		"Arnaud Rebotini",
		"Beatking",
		"Benjamin Diamond",
		"Black",
		"Black Devil Disco Club",
		"Borussia",
		"Boston Bun",
		"Brodinski",
		"Caleon Fox",
		"Chateau Marmont",
		"Chloé",
		"Cosmo Vitelli",
		"Coubo",
		"DJ Pone",
		"Demon",
		"Diane Tell",
		"Don Krez",
		"Esthero",
		"Fatboy Slim",
		"Feadz",
		"Fulgeance",
		"Great Big Sea",
		"Joakim",
		"Krazy Baldhead",
		"Krzysztof Komeda",
		"Kyary Pamyu Pamyu",
		"Lifelike",
		"Lovelock",
		"Marble Players",
		"Mark Ronson",
		"Mercuzio Pianist",
		"Mondkopf",
		"Moriarty",
		"Nena",
		"Oxia",
		"Para One",
		"Pierre Perpall",
		"Placebo",
		"Prayers",
		"Richard Hall",
		"Saib",
		"Samwise",
		"Schlong",
		"Shazam",
		"Some",
		"Soupir",
		"Spirit Of The West",
		"Spoon",
		"Steve Miller Band",
		"Surkin",
		"Teki Latex",
		"The Gap Band",
		"The Kingsmen",
		"The Supermen Lovers",
		"The Whispers",
		"Wet Wet Wet",
		"eevee",
		"of Montreal",
		"sophie meiers",
	],
	"Gangsta Rap": [
		"Big L",
		"Eazy-E",
		"Geto Boys",
		"Ice Cube",
		"N.W.A.",
		"Nas",
		"Onyx",
		"Project Pat",
	],
	"Mumble Rap": [
		"Blueface",
		"Future",
		"Kodak Black",
		"Lil Baby",
		"Lil Uzi Vert",
		"Lil Yachty",
		"Playboi Carti",
		"Young Thug",
		"YoungBoy Never Broke Again",
	],
	"Hard Rap": [
		"$uicideBoy$",
		"6ix9ine",
		"A$AP Ferg",
		"Big Baby Scumbag",
		"Blueface",
		"Bobby Shmurda",
		"Busta Rhymes",
		"D Double E",
		"DaBaby",
		"Danny Brown",
		"Dorrough Music",
		"Gucci Mane",
		"KNOWN.",
		"Lady Leshurr",
		"Lil Baby",
		"Lil Uzi Vert",
		"Migos",
		"Nadia Rose",
		"OG Maco",
		"Onyx",
		"Project Pat",
		"Rich The Kid",
		"Stormzy",
		"Tay-K",
		"Tempa T",
		"Terror Reid",
		"The Underachievers",
		"Trent the HOOLiGAN",
		"Trinidad James",
		"Wiley",
		"Young Thug",
	],
}
