ARTIST_CATEGORIES = {
    "Hip Hop": [
        "Kodak Black",
        "Trent the HOOLiGAN",
        "City Morgue",
        "Tee Grizzley",
        "Takeoff",
        "Rich The Kid",
        "Lil Baby",
        "Freshie",
        "YBN Nahmir",
        "Chophouze",
        "YoungBoy Never Broke Again",
        "Comethazine",
        "MadeinTYO",
        "Trippie Redd",
        "Tay-K",
        "Lil Yachty",
        "Lil Tecca",
        "YBN Cordae",
        "Blueface",
        "DaBaby",
        "Quality Control",
        "Vince Staples",
        "Trinidad James",
        "Chuuwee",
        "Warren G",
        "Denzel Curry",
        "Riff Raff",
        "100s",
        "2 Chainz",
        "21 Savage",
        "6LACK",
        "6ix9ine",
        "A$AP Ferg",
        "A$AP Mob",
        "A$AP Rocky",
        "Ab-Soul",
        "Aesop Rock",
        "Andre Nickatina",
        "Anti-Lilly & Phoniks",
        "BJ The Chicago Kid",
        "Beastie Boys",
        "Big Boi",
        "Big K.R.I.T.",
        "Big L",
        "Big Pun",
        "Big Sean",
        "Big Shaq",
        "Big Tuck",
        "Bishop Nehru",
        "Bobby Shmurda",
        "Boogie",
        "Bryson Tiller",
        "Busta Rhymes",
        "Cardi B",
        "Childish Gambino",
        "Chuggo",
        "Curren$y",
        "Danger Doom",
        "Danny Brown",
        "Dave",
        "Dead Prez",
        "Death Grips",
        "Del The Funky Homosapien",
        "Deltron 3030",
        "Devin The Dude",
        "Die Antwoord",
        "Doobmin",
        "Doom",
        "Doron Lev",
        "Dorrough Music",
        "Dr. Dre",
        "Drake",
        "Dreezy",
        "Dusty Ohms",
        "EARTHGANG",
        "Ed Scissor",
        "Eminem",
        "Evil Nine / Aesop Rock",
        "Fetty Wap",
        "Flatbush Zombies",
        "Flying Lotus",
        "Freddie Gibbs",
        "Future",
        "G Perico",
        "Geto Boys",
        "Gmcfosho",
        "Gnarls Barkley",
        "Hail Mary Mallon",
        "Handsome Boy Modeling School",
        "Ice Cube",
        "Innanet James",
        "Isaiah Rashad",
        "J Capri",
        "J Dilla",
        "J Hus",
        "J.R. Donato",
        "JAY-Z",
        "JID",
        "Jay Rock",
        "Jidenna",
        "Jody HiGHROLLER",
        "Joey Bada$$",
        "Juice WRLD",
        "K.M.D.",
        "Kanye West",
        "Kendrick Lamar",
        "Kholebeatz",
        "King Geedorah",
        "Knowmadic",
        "Leakaveli",
        "Lil Dicky",
        "Lil Toe",
        "Lil Uzi Vert",
        "Lil Whyte",
        "Lil Windex",
        "Lil Wyte",
        "MC Chris",
        "MF DOOM",
        "Migos",
        "Mike WiLL Made-It",
        "Montell Jordan",
        "Nas",
        "Nipsey Hussle",
        "O.T. Genasis",
        "OG Maco",
        "OJ Da Juiceman",
        "Odd Future",
        "Onoe Caponoe",
        "Onyx",
        "OutKast",
        "Pimp C",
        "Playboi Carti",
        "Project Pat",
        "Quasimoto",
        "Quin Nfn",
        "Rae Sremmurd",
        "Redman",
        "Rich Homie Quan",
        "ScHoolboy Q",
        "Sir Mix-A-Lot",
        "Skee-Lo",
        "Ski Mask The Slump God",
        "Suga Free",
        "Swindle",
        "Talib Kweli",
        "Tall Black Guy",
        "Terror Reid",
        "Tha Dogg Pound",
        "The Game",
        "The Lonely Island",
        "The Notorious B.I.G.",
        "The Pharcyde",
        "The Underachievers",
        "Tommy Cash",
        "Travis Scott",
        "Trick Daddy",
        "Tyler, The Creator",
        "UnoTheActivist",
        "Viktor Vaughn",
        "Waka Flocka Flame",
        "Wu-Tang Clan",
        "XXXTENTACION",
        "Young Thug",
        "Zebra Katz",
        "$uicideBoy$",
        "Dom Kennedy",
        "Aloe Blacc",
        "Blood Orange",
        "CL",
    ],
    "Grime": [
        "Dizzee Rascal",
        "Stormzy",
        "Wiley",
        "D Double E",
        "AJ Tracey",
        "Bugzy Malone",
        "Flowdan",
        "Jammer",
        "Jme",
        "Kano",
        "Lady Leshurr",
        "Milli Major",
        "Nadia Rose",
        "Paigey Cakey",
        "President T",
        "Pusha T",
        "Riddim Commission",
        "Skepta",
        "Zuse",
        "Uncle Murda",
        "Tempa T",
    ],
    "Electronic": [
        "Beck",
        "Daft Punk",
        "Crystal Castles",
        "Becky Hill",
        "Boys Noize",
        "Cassius",
        "Digitalism",
        "Diplo",
        "Flight Facilities",
        "Gorillaz",
        "LCD Soundsystem",
        "MSTRKRFT",
        "Malaa",
        "Mercer",
        "MiM0SA",
        "Moby",
        "Oliver",
        "Oliver Heldens",
        "Pretty Lights",
        "Shiba San",
        "The Octopus Project",
        "Yello",
        "Baauer",
        "KRANE",
    ],
    "DnB": ["Pendulum", "Andy C"],
    "Synthwave": [
        "Com Truise",
        "Kavinsky",
        "Dan Terminus",
        "Carpenter Brut",
        "Dance With the Dead",
        "Fukkk Offf",
        "Gesaffelstein",
        "Blank Banshee",
    ],
    "Rock": [
        "Art vs Science",
        "The Hives",
        "The Voidz",
        "The White Stripes",
        "Queens of the Stone Age",
        "Red Hot Chili Peppers",
        "The Mars Volta",
    ],
    "Chiptunes": ["MisfitChris", "Fantomenk"],
    "French Electro": [
        "Siriusmo",
        "Breakbot",
        "Mr. Oizo",
        "Riton",
        "SebastiAn",
        "Sébastien Tellier",
        "Chromeo",
    ],
    "Synth Pop": ["Gary Numan", "Kraftwerk", "Thomas Dolby",],
    "New Wave": ["New Order", "Joy Division",],
    "Heavy": [
        "All That Remains",
        "Mindless Self Indulgence",
        "Gojira",
        "Lamb of God",
        "Mastodon",
        "Death From Above 1979",
        "The Fall of Troy",
        "Protest The Hero",
    ],
    "Jazz": ["Yusef Lateef", "The Deli", "Twin Danger",],
    "Chill": ["Jonwayne", "Mndsgn", "Sleepdealer", "Wun Two", "[bsd.u]",],
    "Oldies": [
        "Age of Consent",
        "David Bowie",
        "Chaka Khan",
        "The O'Jays",
        "Bill Withers",
        "The Clash",
        "Marvin Gaye",
        "The Doors",
        "Yaz",
        "a-ha",
        "Billy Idol",
        "Cameo",
        "Depeche Mode",
        "Don Henley",
        "Duran Duran",
        "Dusty Springfield",
        "Laura Branigan",
        "Men Without Hats",
        "Elton John",
        "Michael Jackson",
        "Otis Redding",
        "Pet Shop Boys",
        "Pixies",
        "Queen",
        "The Police",
        "The Supremes",
        "The Temptations",
        "Rick Astley",
        "Rick James",
        "Jethro Tull",
        "Jimi Hendrix",
        "Kenny Loggins",
        "Oingo Boingo",
        "Stereolab",
        "Stevie Wonder",
        "Styx",
        "Supertramp",
    ],
    "Reggae": ["Beenie Man", "Gappy Ranks", "Red Rat",],
    "Prog": ["Emerson, Lake & Palmer", "Gentle Giant"],
}
