ARTIST_CATEGORIES = {
	"Hip Hop": [
		"Kodak Black",
		"Trent the HOOLiGAN",
		"City Morgue",
		"Tee Grizzley",
		"Takeoff",
		"Rich The Kid",
		"Lil Baby",
		"Freshie",
		"YBN Nahmir",
		"Chophouze",
		"YoungBoy Never Broke Again",
		"Comethazine",
		"MadeinTYO",
		"Trippie Redd",
		"Tay-K",
		"Lil Yachty",
		"Lil Tecca",
		"YBN Cordae",
		"Blueface",
		"DaBaby",
		"Quality Control",
		"Vince Staples",
		"Trinidad James",
		"Chuuwee",
		"Warren G",
		"Denzel Curry",
		"Riff Raff",
		"100s",
		"2 Chainz",
		"21 Savage",
		"6LACK",
		"6ix9ine",
		"A$AP Ferg",
		"A$AP Mob",
		"A$AP Rocky",
		"Ab-Soul",
		"Aesop Rock",
		"Andre Nickatina",
		"Anti-Lilly & Phoniks",
		"BJ The Chicago Kid",
		"Beastie Boys",
		"Big Boi",
		"Big K.R.I.T.",
		"Big L",
		"Big Pun",
		"Big Sean",
		"Big Shaq",
		"Big Tuck",
		"Bishop Nehru",
		"Bobby Shmurda",
		"Boogie",
		"Bryson Tiller",
		"Busta Rhymes",
		"Cardi B",
		"Childish Gambino",
		"Chuggo",
		"Curren$y",
		"Danger Doom",
		"Danny Brown",
		"Dave",
		"Dead Prez",
		"Death Grips",
		"Del The Funky Homosapien",
		"Deltron 3030",
		"Devin The Dude",
		"Die Antwoord",
		"Doobmin",
		"Doom",
		"Doron Lev",
		"Dorrough Music",
		"Dr. Dre",
		"Drake",
		"Dreezy",
		"Dusty Ohms",
		"EARTHGANG",
		"Ed Scissor",
		"Eminem",
		"Evil Nine / Aesop Rock",
		"Fetty Wap",
		"Flatbush Zombies",
		"Flying Lotus",
		"Freddie Gibbs",
		"Future",
		"G Perico",
		"Geto Boys",
		"Gmcfosho",
		"Gnarls Barkley",
		"Hail Mary Mallon",
		"Handsome Boy Modeling School",
		"Ice Cube",
		"Innanet James",
		"Isaiah Rashad",
		"J Capri",
		"J Dilla",
		"J Hus",
		"J.R. Donato",
		"JAY-Z",
		"JID",
		"Jay Rock",
		"Jidenna",
		"Jody HiGHROLLER",
		"Joey Bada$$",
		"Juice WRLD",
		"K.M.D.",
		"Kanye West",
		"Kendrick Lamar",
		"Kholebeatz",
		"King Geedorah",
		"Knowmadic",
		"Leakaveli",
		"Lil Dicky",
		"Lil Toe",
		"Lil Uzi Vert",
		"Lil Whyte",
		"Lil Windex",
		"Lil Wyte",
		"MC Chris",
		"MF DOOM",
		"Migos",
		"Mike WiLL Made-It",
		"Montell Jordan",
		"Nas",
		"Nipsey Hussle",
		"O.T. Genasis",
		"OG Maco",
		"OJ Da Juiceman",
		"Odd Future",
		"Onoe Caponoe",
		"Onyx",
		"OutKast",
		"Pimp C",
		"Playboi Carti",
		"Project Pat",
		"Quasimoto",
		"Quin Nfn",
		"Rae Sremmurd",
		"Redman",
		"Rich Homie Quan",
		"ScHoolboy Q",
		"Sir Mix-A-Lot",
		"Skee-Lo",
		"Ski Mask The Slump God",
		"Suga Free",
		"Swindle",
		"Talib Kweli",
		"Tall Black Guy",
		"Terror Reid",
		"Tha Dogg Pound",
		"The Game",
		"The Lonely Island",
		"The Notorious B.I.G.",
		"The Pharcyde",
		"The Underachievers",
		"Tommy Cash",
		"Travis Scott",
		"Trick Daddy",
		"Tyler, The Creator",
		"UnoTheActivist",
		"Viktor Vaughn",
		"Waka Flocka Flame",
		"Wu-Tang Clan",
		"XXXTENTACION",
		"Young Thug",
		"Zebra Katz",
		"$uicideBoy$",
		"Dom Kennedy",
		"Aloe Blacc",
		"Blood Orange",
		"CL",
		"Babu",
		"Joji",
		"Big Baby Scumbag",
		"Chaz",
		"Foreign Beggars",
		"Smoke Boys",
		"M.O.P.",
		"Slick Rick",
		"Denzil Porter",
		"Fatboy Slim",
		"LL Cool J",
		"Public Enemy",
		"Method Man",
		"Mos Def",
		"DMX",
		"GZA",
		"Ghostface Killah",
		"50 Cent",
		"Salt-N-Pepa",
		"Eighth Wonder",
		"Gang Starr",
		"Ja Rule",
		"Sheck Wes",
		"Nebu Kiniza",
		"Young M.A",
		"3rd Bass",
		"ASM",
		"Akua Naru",
		"Apollo Brown",
		"Arrested Development",
		"Black Sheep",
		"Black Star",
		"Chester Watson",
		"Count Bass D",
		"DJ Snake",
		"Declaime",
		"Digable Planets",
		"EPMD",
		"Eric B. & Rakim",
		"Footsie",
		"Gangrene",
		"Guru",
		"Hell Razah",
		"IDK",
		"ILL Bill",
		"Ivan Ave",
		"JACKBOYS",
		"Jaykae",
		"Jazz Spastiks",
		"Jeru The Damaja",
		"John Robinson",
		"Josef Leimberg",
		"Kev Brown",
		"King Tee",
		"Krush",
		"L-Boy",
		"Leaders of the New School",
		"Low Profile",
		"Mack 10",
		"Marion Band$",
		"Masta Killa",
		"Mick Jenkins",
		"Nice & Smooth",
		"Oh No",
		"OverDoz.",
		"Pharoahe Monch",
		"Positive K",
		"Rabbi Shlomo",
		"Ronny J",
		"Scarface",
		"Scienz Of Life",
		"Spice 1",
		"Steve G. Lover III",
		"Terror Squad",
		"The Prof",
		"The Roots",
		"Tony J. Guy",
		"Tree",
		"Tunji Ige",
		"Twista",
		"UGK",
		"Vast Aire",
		"WELL$",
		"Wax",
		"Wc And The Maad Circle",
		"Weerd Science",
		"Wildchild",
	],
	"Grime": [
		"Dizzee Rascal",
		"Stormzy",
		"Wiley",
		"D Double E",
		"AJ Tracey",
		"Bugzy Malone",
		"Flowdan",
		"Jammer",
		"Jme",
		"Kano",
		"Lady Leshurr",
		"Milli Major",
		"Nadia Rose",
		"Paigey Cakey",
		"President T",
		"Pusha T",
		"Riddim Commission",
		"Skepta",
		"Zuse",
		"Uncle Murda",
		"Tempa T",
	],
	"Electronic": [
		"Beck",
		"Daft Punk",
		"Crystal Castles",
		"Becky Hill",
		"Boys Noize",
		"Cassius",
		"Digitalism",
		"Diplo",
		"Flight Facilities",
		"Gorillaz",
		"LCD Soundsystem",
		"MSTRKRFT",
		"Malaa",
		"Mercer",
		"MiM0SA",
		"Moby",
		"Oliver",
		"Oliver Heldens",
		"Pretty Lights",
		"Shiba San",
		"The Octopus Project",
		"Yello",
		"Baauer",
		"KRANE",
		"Busy P",
		"DJ Blyatman",
		"Flosstradamus",
		"Jacuzzi",
		"Rustie",
		"The Prodigy",
		"Alvaro",
		"Danger",
		"Destructo",
		"Electronic",
		"Favored Nations",
		"Groove Armada",
		"HEALTH",
		"M-Beat",
		"MK",
		"Maelstrom",
		"Matoma",
		"Mighty Dub Katz",
		"State of Mind",
		"The Chain Gang Of 1974",
		"The Hacker",
		"The Jungle Giants",
		"Toro y Moi",
		"Valentino Khan",
		"X-Press 2",
		"Delta Heavy",
	],
	"Indie": [
		"Cake",
		"Chad VanGaalen",
		"Neutral Milk Hotel",
		"The Strokes",
		"Devendra Banhart",
		"Modest Mouse",
		"Metronomy",
		"Sunset Rubdown",
		"Vampire Weekend",
		"Neon Indian",
		"Edie Brickell & New Bohemians",
		"José González",
		"Peter Bjorn and John",
		"The Burning Hell",
		"Yeasayer",
	],
	"Computer Music": [
		"Kraftwerk",
		"Nobukazu Takemura",
		"Rei Harakami",
	],
	"DnB": [
		"Pendulum",
		"Andy C",
	],
	"Synthwave": [
		"Com Truise",
		"Kavinsky",
		"Dan Terminus",
		"Carpenter Brut",
		"Dance With the Dead",
		"Fukkk Offf",
		"Gesaffelstein",
		"Blank Banshee",
		"Kn1ght",
		"Scattle",
		"The Toxic Avenger",
		"Waveshaper",
	],
	"Rock": [
		"Art vs Science",
		"The Hives",
		"The Voidz",
		"The White Stripes",
		"Queens of the Stone Age",
		"Red Hot Chili Peppers",
		"The Mars Volta",
		"Tenacious D",
		"The Ataris",
		"OFF!",
		"Wavves",
		"Primus",
	],
	"Chiptunes": [
		"MisfitChris",
		"Fantomenk",
		"Dubmood",
		"FantomenK",
	],
	"French Electro": [
		"Justice",
		"Siriusmo",
		"Breakbot",
		"Mr. Oizo",
		"Riton",
		"SebastiAn",
		"Sébastien Tellier",
		"Chromeo",
	],
	"Synth Pop": [
		"Gary Numan",
		"Depeche Mode",
		"Kraftwerk",
		"Thomas Dolby",
		"Dolby's Cube",
	],
	"New Wave": [
		"New Order",
		"Joy Division",
		"The B-52's",
		"Nite Jewel",
	],
	"Heavy": [
		"Death Grips",
		"All That Remains",
		"Mindless Self Indulgence",
		"Gojira",
		"Lamb of God",
		"Mastodon",
		"Death From Above 1979",
		"The Fall of Troy",
		"Protest The Hero",
		"Billx",
		"Alexisonfire",
		"Drive Like Jehu",
		"Periphery",
	],
	"Jazz": [
		"Yusef Lateef",
		"The Deli",
		"Twin Danger",
		"Fela Kuti",
		"Ryuichi Sakamoto",
		"Takuya Kuroda",
		"Yazz",
	],
	"Chill": [
		"Jonwayne",
		"Boards of Canada",
		"Mndsgn",
		"Sleepdealer",
		"Wun Two",
		"[bsd.u]",
		"Hexsystem",
		"Brock Berrigan",
		"Clap! Clap!",
		"Ancient Astronauts",
		"Lorn",
		"Nosaj Thing",
	],
	"Oldies": [
		"Age of Consent",
		"David Bowie",
		"Chaka Khan",
		"The O'Jays",
		"Bill Withers",
		"Carmen",
		"Deep Purple",
		"Jamiroquai",
		"Tom Waits",
		"The Clash",
		"Marvin Gaye",
		"The Doors",
		"Yaz",
		"a-ha",
		"Billy Idol",
		"Cameo",
		"Funkadelic",
		"Toba",
		"Don Henley",
		"Smokey Robinson & The Miracles",
		"Duran Duran",
		"Bruce Springsteen",
		"Dusty Springfield",
		"Laura Branigan",
		"Men Without Hats",
		"Elton John",
		"Michael Jackson",
		"Otis Redding",
		"Pet Shop Boys",
		"Pixies",
		"Queen",
		"The Police",
		"The Supremes",
		"The Temptations",
		"Rick Astley",
		"Rick James",
		"Jethro Tull",
		"Jimi Hendrix",
		"Kenny Loggins",
		"Oingo Boingo",
		"Stereolab",
		"Stevie Wonder",
		"Styx",
		"Supertramp",
		"Magazine",
		"New Kids On The Block",
		"Boy George",
		"Tears For Fears",
		"Melody's Echo Chamber",
		"Aswad",
		"Boogie Boys",
		"Bros",
		"Bruce Willis",
		"Corey Hart",
		"Curiosity Killed The Cat",
		"Deacon Blue",
		"Dâm-Funk",
		"Fairground Attraction",
		"Four Tops",
		"Frazier Chorus",
		"Hue and Cry",
		"Ivana Spagna",
		"Gustav Holst",
		"Kurtis Blow",
		"Kylie Minogue",
		"Level 42",
		"Los Lobos",
		"Malcolm McLaren & The Bootzilla Orchestra",
		"Prefab Sprout",
		"Rick Springfield",
		"Roachford",
		"Sam Brown",
		"Samantha Fox",
		"Shakin' Stevens",
		"Simply Red",
		"Sonia",
		"Soul II Soul",
		"Sporto Kantès",
		"T'Pau",
		"Taylor Dayne",
		"Terence Trent D'Arby",
		"The Darling Buds",
		"The Pasadenas",
		"The Primitives",
		"The Reynolds Girls",
		"The Stranglers",
		"Tiffany",
		"Transvision Vamp",
		"Twin Shadow",
		"Westworld",
		"Wilson Pickett",
	],
	"Reggae": [
		"Beenie Man",
		"Gappy Ranks",
		"Red Rat",
		"Gregory Isaacs",
		"Buju Banton",
		"Max Romeo",
		"Maxi Priest",
	],
	"Prog": [
		"Emerson, Lake & Palmer",
		"Gentle Giant",
	],
	"IGNORE": [
		"Nena",
		"Don Krez",
		"Richard Hall",
		"The Whispers",
		"The Gap Band",
		"Beatking",
		"of Montreal",
		"Steve Miller Band",
		"The Kingsmen",
		"Schlong",
		"88rising",
		"Mercuzio Pianist",
		"sophie meiers",
		"Moriarty",
		"Spirit Of The West",
		"Caleon Fox",
		"Boston Bun",
		"Fulgeance",
		"DJ Pone",
		"Feadz",
		"Krazy Baldhead",
		"Borussia",
		"Para One",
		"10LEC6",
		"Some",
		"Pierre Perpall",
		"Lovelock",
		"Chateau Marmont",
		"Soupir",
		"Lifelike",
		"Shazam",
		"Diane Tell",
		"Great Big Sea",
		"Esthero",
		"Spoon",
		"Saib",
		"Coubo",
		"eevee",
		"Samwise",
		"Alex Gopher",
		"Demon",
		"Benjamin Diamond",
		"Cosmo Vitelli",
		"The Supermen Lovers",
		"Alan Braxe",
		"Marble Players",
		"Acid Washed",
		"Black Devil Disco Club",
		"Mondkopf",
		"Surkin",
		"Brodinski",
		"Chloé",
		"Oxia",
		"Joakim",
		"Teki Latex",
		"Agoria",
		"Arnaud Rebotini",
		"Krzysztof Komeda",
		"Black",
		"Kyary Pamyu Pamyu",
		"Mark Ronson",
		"Placebo",
		"Prayers",
		"Wet Wet Wet",
	],
	"Gangsta Rap": [
		"N.W.A.",
		"Nas",
		"Big L",
		"Eazy-E",
		"Ice Cube",
		"Project Pat",
		"Geto Boys",
		"Onyx",
	],
	"Mumble Rap": [
		"Lil Uzi Vert",
		"Playboi Carti",
		"Lil Yachty",
		"YoungBoy Never Broke Again",
		"Blueface",
		"Future",
		"Young Thug",
		"Kodak Black",
		"Lil Baby",
	],
	"Hard Rap": [
		"6ix9ine",
		"A$AP Ferg",
		"Big Baby Scumbag",
		"Blueface",
		"Bobby Shmurda",
		"Busta Rhymes",
		"DaBaby",
		"Danny Brown",
		"Dorrough Music",
		"Gucci Mane",
		"KNOWN.",
		"Lady Leshurr",
		"Lil Baby",
		"Lil Uzi Vert",
		"Migos",
		"Nadia Rose",
		"OG Maco",
		"Onyx",
		"Project Pat",
		"Rich The Kid",
		"Stormzy",
		"Tay-K",
		"Tempa T",
		"D Double E",
		"Terror Reid",
		"Trent the HOOLiGAN",
		"Trinidad James",
		"$uicideBoy$",
		"The Underachievers",
		"Wiley",
		"Young Thug",
	],
}
