genres = {
    "Hip-Hop": [
        "hip-hop",
        "mumble rap",
        "dirty south",
        "hip hop",
        "rap",
        "trap",
        "swagswagswag",
        "pimp",
        "guns",
        "da real underground new skool hip hop",
        "true hip hop",
        "underground hip hop",
        "southern rap",
        "horrorcore",
        "experimental hip-hop",
        "post rap",
        "trip-hop",
        "trip hop",
        "glitch-hop",
        "glitch hop",
        "psychadelic rap",
        "instrumental hip-hop",
        "hip hop tag",
        "post-nerdcore",
        "seal-hop",
        "gangsta rap",
        "trap rap",
        "hardcore hip hop",
        "hiphop - east coast",
        "chilled hip hop",
        "black hippy",
        "indie rap",
        "indie hip hop",
        "alternative hip hop",
        "detroit hip hop",
        "new rap",
        "michigan rap",
        "hood classic",
        "jazz rap",
        "conscious hip hop",
        "west coast hip hop",
        "2 chains",
        "2 chainz",
        "6ix9ine",
        "ab-soul",
        "aj tracey",
        "alchemist",
        "ball so hard",
        "bj the chicago kid",
        "blow some money music",
        "bryson tiller",
        "cold december flow",
        "cocaine in the bed",
        "concious hiphop",
        "dababy",
        "danny brown -juno",
        "devin the dude",
        "devon the dude",
        "dj mustard",
        "dope beat",
        "dope peddler",
        "earl sweatshirt",
        "fetty wap",
        "frank ocean",
        "future",
        "gucci mane",
        "gucci",
        "gunna",
        "he is madlib and he makes music",
        "hip hop tag",
        "hip-hop?",
        "i luv them strippers",
        "jay rock",
        "juice wrld",
        "juice wrld",
        "kanye west",
        "kendrick lamar",
        "kid cudi",
        "kodak black",
        "lil baby",
        "lil dicky",
        "meek mill",
        "mf doom",
        "metro downtempo",
        "migos",
        "mndsn",
        "music to get the pussy wet",
        "offset",
        "ofwgkta",
        "pi'erre bourne",
        "project pat dawg",
        "produced by organized noize",
        "purple hulk",
        "qc",
        "quality control music",
        "quality control",
        "quavo",
        "rhythm and poetry",
        "rich homie quan",
        "rich the kid",
        "ski mask the slump god",
        "southern",
        "spoken words jewelz",
        "spoken word",
        "strippers",
        "swag",
        "the d",
        "tony montana",
        "travis scott",
        "trippie redd",
        "vercase",
        "vercaseversace",
        "versace",
        "versaceversaceversaceversaceversaceversaceversaceversace",
        "weed party",
        "weed smokers anthem",
        "weezy f aka yancy tate",
        "west coast rap",
        "wu-tang clan",
        "ybn nahmir",
        "yg",
        "young scooter",
        "young scooter",
        "young thug",
        "young thug",
        "21 savage",
        "busta rhymes",
        "rick ross",
        "snoop dogg",
        "asap rocky",
        "french montana",
        "dave east",
        "lex luger",
        "6lack",
        "xxxtentacion",
        "psychedelic hip hop",
        "psychedelic rap",
    ],
    "Metal": [
        "metal",
        "brutal",
        "rap metal",
        "heavy metal",
        "post-hardcore",
        "mathcore",
        "metalcore",
        "progressive metal",
        "technical metal",
        "experimental metalcore",
        "progressive metalcore",
        "math metal",
        "power metal",
        "avant-garde metal",
        "melodic metalcore",
        "technical metalcore",
        "math-core",
        "sludge metal",
        "prog",
        "some heavy shit",
        "hardcore",
    ],
    "Rock": [
        "rock",
        "alternative rock",
        "indie rock",
        "progressive rock",
        "90s rock",
        "art rock",
        "space rock",
        "experimental rock",
        "indie",
        "synth rock",
        "tween rock",
        "1980s: dance rock",
        "genre: funk rock",
        "1980s: funk rock",
        "classic rock",
        "progressive",
    ],
    "Pop": [
        "pop rock",
        "indie pop",
        "pop",
        "synthpop",
        "electropop",
        "elektropop",
        "pop punk",
        "pop experimental",
        "genre: pop rock",
        "1980s: pop rock",
        "1980s: synth pop",
        "genre: synth pop",
    ],
    "Electronic": [
        "electronic",
        "electronica",
        "trance",
        "house",
        "disco",
        "nu rave",
        "dubstep",
        "idm",
        "electro",
        "techno",
        "synth",
        "synthesizer",
        "nu-disco",
        "nu disco",
        "italo disco",
        "00s electro",
        "dance",
        "rave",
        "moombahton",
        "clubber",
        "acid jazz",
        "party",
        "edm",
        "tag: dance",
        "drum and bass",
        "dnb",
        "jungle",
    ],
    "Chill": [
        "chill",
        "late night",
        "late-night",
        "chillhop",
        "lo-fi",
        "ambient",
        "atmospheric",
        "mellow shit",
        "chillwave",
        "smoking music",
        "chilled",
        "downtempo",
        "chill out",
    ],
    "Synthwave": [
        "synthwave",
        "new wave",
        "vaporwave",
        "vaportrap",
        "genre: new wave",
        "1980s: new wave",
        "new wave peppermint",
        "wave trap",
    ],
    "Grime": ["grime"],
    "Funk": ["funk", "funky", "electrofunk"],
    "Soul": ["soul", "pure soul", "soulful", "blues"],
    "Jazz": ["jazz", "polish jazz", "contemporary jazz"],
    "Industrial": ["industrial"],
    "Punk": ["punk", "electropunk", "synthpunk"],
    "Reggae": ["ragga", "roots reggae", "dub", "roots"],
    "Folk": ["folk", "singer-songwriter"],
    "Country": ["country"],
    "Soundtrack": ["soundtrack", "filmmusik", "horror soundtrack"],
}

genre_blacklist = [
    "remember me",
    "kocham lubie szanuje",
    "morrencia",
    "happy in the title",
    "2-14-19",
    "sexy",
    "1",
    "1-6-19",
    "100",
    "10o0o0o",
    "10s",
    "13 reasons why",
    "170 ooo",
    "1992",
    "2",
    "2010s",
    "2011",
    "2012",
    "2013",
    "2014",
    "2015 single",
    "2016 single",
    "2016",
    "2017 single",
    "2018",
    "2018",
    "21st century in music",
    "3-13-19",
    "3-6-19",
    "30 09 2013",
    "4 star",
    "5 of 10 stars",
    "5 stars",
    "9-23-19",
    "90s",
    "9207",
    "9p",
    "a w e s o m ez",
    "aaargh",
    "aberrant mental states",
    "amazing",
    "american",
    "animals",
    "anissa kate",
    "at the end of the world",
    "ava addams",
    "avant-garde",
    "awesome covers",
    "awesome",
    "b e r r i e s ii",
    "b e s t o f f m",
    "bagel",
    "bajki z jowisza",
    "balafon",
    "banger",
    "banned by spotify2017",
    "banned",
    "bass",
    "bassists",
    "basss",
    "bb",
    "bbc radio1 playlist 2016",
    "bbc6",
    "beat sick af",
    "beats",
    "beaver",
    "bee gees cover",
    "bee gees",
    "best covers",
    "best of 2009",
    "best of 2011",
    "best song ever made",
    "better than one direction",
    "bibi noel",
    "big",
    "billy wedding",
    "billy wedding",
    "bing bing massive tune",
    "boonville",
    "bow",
    "break my heart",
    "bridge",
    "british columbia",
    "british",
    "brocklyn bridge",
    "brom",
    "brown",
    "bs",
    "c h e r i e",
    "catchy",
    "clanddi jinkcego",
    "colbert",
    "color",
    "computer",
    "control system",
    "cover cover",
    "cover version",
    "cover",
    "cream",
    "crocker",
    "curious",
    "dancing the night away",
    "dark",
    "day bow bow",
    "days and nights",
    "days and nights",
    "de",
    "debo",
    "deepnight",
    "deja vu",
    "derby",
    "design",
    "detroit",
    "dl",
    "drk",
    "duo",
    "electroclash",
    "electronic superhighway",
    "elektronic beats",
    "emotional",
    "english lyrics",
    "english-language",
    "eva karera",
    "experimental",
    "fabric",
    "fallon",
    "fashion",
    "fav track",
    "favorites 2013",
    "favorites",
    "favourite remixes",
    "faygo",
    "female vocalists",
    "fever",
    "fip",
    "first name",
    "fm4",
    "fotomotor",
    "fotomotor-auto",
    "four foot shack",
    "four",
    "french",
    "fucking awesome",
    "funny",
    "futins favourite hop",
    "fye",
    "g r e a t",
    "gamelan",
    "gay",
    "gesamt 7 2012",
    "gilles peterson",
    "girl",
    "good bass",
    "good intro for a mixtape",
    "good stuff",
    "gossip",
    "grand theft auto",
    "great story",
    "great",
    "greggotti",
    "gta 5",
    "gta san andreas liberty-reallife",
    "gta v",
    "happy",
    "hard shit",
    "heavy bass line",
    "holly",
    "holy shit",
    "horses and ponies and unicorns too",
    "i should buy this",
    "ice",
    "imma do it fa show",
    "incredible",
    "instrumental",
    "io sono piace",
    "itunes uk single of the week",
    "j u w e l e n",
    "jamiroquai",
    "japan trance",
    "jerry was a race car driver",
    "jessie volt",
    "jessyca wilson",
    "job",
    "johnny horton cover",
    "johnny horton",
    "jordan hawkins",
    "just dance",
    "justdontgiveafuck",
    "k1r7m",
    "karmickoala",
    "kat fm",
    "kling klang",
    "kss1984 - good",
    "kss1984 - great",
    "kss1984 - loved",
    "l i e bling",
    "l",
    "lea lazur",
    "leapsandbounds cdcollection",
    "les claypool",
    "les claypool-s duo de twang",
    "les claypools duo de twang",
    "life and death",
    "life and how to do it",
    "like a lot",
    "liked",
    "live",
    "liza del sierra",
    "long songs",
    "love",
    "lust demons",
    "luved",
    "magic male voice",
    "make it brief son half short and twice strong",
    "male vocalist",
    "mary",
    "mea m",
    "meabsolutfav",
    "media player library",
    "melancholic",
    "melhor de 2009",
    "meyers",
    "miasto we mgle",
    "minimal",
    "minimalism",
    "minimalist",
    "missing someone",
    "modern classical",
    "mohansen tom",
    "montanaave",
    "motivation music",
    "mountains and hills and volcanoes and valleys",
    "mtg gold",
    "mtg gold",
    "my favourite",
    "mylounge",
    "name",
    "names of people",
    "natasha nice",
    "neo japanesque",
    "new hope in wv",
    "not electro",
    "not get wet (x3)",
    "oh no",
    "omelet",
    "opelmelange",
    "outro",
    "paint",
    "parts of the body",
    "parts of the body",
    "personal favourites",
    "pito",
    "pl funky vol 2",
    "played",
    "pocahontas",
    "poetry",
    "poles",
    "police and thieves",
    "pretty bad",
    "primus cover",
    "primus",
    "prospect1995",
    "przenumer",
    "pure art",
    "qwerty101-dt",
    "r98000 station 13",
    "race traitor",
    "radio mirror park",
    "rain",
    "red states and blue states",
    "reductionism",
    "reggae",
    "relate with that",
    "rivers and seas",
    "rollin",
    "rooties 91000er tl",
    "s'il vaus plait",
    "sad",
    "sample use",
    "sex",
    "sick beat",
    "sick",
    "silence",
    "simons favorites",
    "size",
    "sleepy",
    "smokey",
    "so good",
    "so sad",
    "somafm",
    "song of the day",
    "song",
    "songs for a first date",
    "soty",
    "speak 2 me in the language of music",
    "spongebob",
    "spooky",
    "stayin alive",
    "staying alive",
    "stella delcroix",
    "stomp",
    "strictly for the underground",
    "style",
    "sun and moon and stars and outer space",
    "swamp",
    "swampy",
    "sxsw 2017",
    "sxsw 2017",
    "t-waits",
    "tag",
    "talk",
    "telling times",
    "tellmesound s",
    "that",
    "the battle of new orleans",
    "the chantays cover",
    "the chantays",
    "the good stuff",
    "the sea",
    "the take off",
    "theboyz",
    "they graze",
    "thrillchill",
    "tight beat",
    "tight shit of 07",
    "title is a full sentence",
    "tom lehrer",
    "totally awesome",
    "trapgaze",
    "trippy",
    "tt",
    "uh oh",
    "up the seapunxxx",
    "walzer",
    "warm",
    "winona",
    "witch house",
    "wynona-s big brown beaver",
    "yahya el-zein",
    "yancy tate",
    "you should quit smoking",
    "yyaaaa",
    "zombies",
    "нейрогопак",
    "roaming the globe",
]

artist_category = {
    "Hip-Hop": [
        "Ed Scissor",
        "Jonwayne",
        "Future",
        "OG Maco",
        "Onoe Caponoe",
        "Migos",
        "The Underachievers",
        "Doobmin",
        "Big Tuck",
        "Mndsgn",
        "Kodak Black",
        "Trent the HOOLiGAN",
        "City Morgue",
        "Trinidad James",
        "Boogie",
        "Project Pat",
        "Blueface",
        "Freshie",
        "Chophouze",
        "MF DOOM",
        "Danger Doom",
        "UnoTheActivist",
        "Chuuwee",
        "Comethazine",
        "YoungBoy Never Broke Again",
        "Tee Grizzley",
        "Swindle",
        "Riff Raff",
        "Hail Mary Mallon",
        "100s",
        "EARTHGANG",
        "Dreezy",
        "Waka Flocka Flame",
        "Tommy Cash",
        "Gappy Ranks",
        "Big Shaq",
        "The Lonely Island",
        "G Perico",
        "Lil Baby",
        "DaBaby",
        "Lil Toe",
        "Nas",
        "Beastie Boys",
        "Smoke Boys",
        "A$AP Ferg",
        "O.T. Genasis",
        "Ice Cube",
        "Flatbush Zombies",
        "Dorrough Music",
        "Milli Major",
        "Quin Nfn",
        "Steve G. Lover III",
        "Don Krez",
        "Quasimoto",
        "Big Boi",
        "Kholebeatz",
        "Lil Wyte",
        "Lil Windex",
        "Beatking",
        "Dorrough Music",
        "Doron Lev",
        "JID",
        "Nipsey Hussle",
        "Freddie Gibbs",
        "Knowmadic",
        "Sleepdealer",
        "Big K.R.I.T.",
        "Wu-Tang Clan",
        "2 Chainz",
        "Curren$y",
        "Fetty Wap",
        "Deltron 3030",
        "Dave",
        "Doom",
        "Dusty Ohms",
        "J Dilla",
        "J Hus",
        "Talib Kweli",
        "Gnarls Barkley",
        "Innanet James",
    ],
    "Rock": [
        "Tenacious D",
        "The Voidz",
        "The Police",
        "Duran Duran",
        "Queen",
        "of Montreal",
        "Elton John",
        "Schlong",
        "Kenny Loggins",
        "Pet Shop Boys",
        "Oingo Boingo",
        "Death From Above 1979",
        "Bruce Springsteen",
        "David Bowie",
    ],
    "Metal": ["Protest The Hero", "The Fall of Troy"],
    "Grime": [
        "Flowdan",
        "Kano",
        "D Double E",
        "Bugzy Malone",
        "Tempa T",
        "Jme",
        "Dizzee Rascal",
    ],
    "Chill": ["[bsd.u]", "Wun Two"],
    "Synthwave": ["Fukkk Offf", "Gesaffelstein", "Com Truise"],
    "Electronic": [
        "MSTRKRFT",
        "SebastiAn",
        "Digitalism",
        "Riton",
        "Billx",
        "Yello",
        "DJ Blyatman",
        "Beck",
        "MiM0SA",
        "Kraftwerk",
        "Justice",
        "Mr. Oizo",
        "Cassius",
        "Breakbot",
        "Boys Noize",
        "eevee",
        "Siriusmo",
        "Sébastien Tellier",
        "Pendulum",
        "Flight Facilities",
        "Becky Hill",
    ],
    "Soundtrack": ["Krzysztof Komeda"],
    "Jazz": ["Yusef Lateef", "Twin Danger", "The Deli"],
    "Funk": ["Jamiroquai"],
}
